base_url = "https://rustic.cloud"
title = "Rustic Music Player"
compile_sass = true
highlight_code = false
build_search_index = false

[extra]
sections = [
    "core.md",
    "providers.md",
    "extensions.md"
]
pages = [
    { title = "Features", links = [{ title = "Providers", page = "providers.md" }, { title = "Applications", page = "applications.md" }, { title = "Extensions", page = "extensions.md" }] },
    { title = "Documentation", link = "https://docs.rustic.cloud" },
    { title = "Downloads", page = "downloads.md" }
]
